"""add type to strategies

Revision ID: 3cda580f0bc4
Revises: 1fd1facebaad
Create Date: 2026-09-26 20:51:18.599714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cda580f0bc4'
down_revision: Union[str, Sequence[str], None] = '1fd1facebaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('type', sa.String(), nullable=False, server_default='trading'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'type')
    # ### end Alembic commands ###
